const http=require('http'),crypto=require('crypto'),{WebSocketServer}=require('ws');
const PORT=Number(process.env.PORT||10000),MAX_ROOMS=128,TTL=1800e3,LETTERS='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const rooms=new Map();
const {Backend}=require('./backend');const backend=new Backend({send:(ws,o)=>send(ws,o)});try{const {Ranked}=require('./ranked/service');backend.attachRanked(new Ranked({send:(ws,o)=>send(ws,o)}));backend.attachCasual(new Ranked({send:(ws,o)=>send(ws,o),kind:'casual'}))}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e}
console.log('FRAIHA accounts backend: '+backend.kind);
// FRAIHA Admin · API /admin/api/* (desligada sem FRAIHA_ADMIN_USERS; autoridade só no servidor). Ver docs/admin/.
const {AdminService}=require('./admin/service');const admin=new AdminService({backend});
// Frontend do Admin em /admin/ (estático, só com o Admin ligado). A API /admin/api/* vem antes. Ver online_v021/admin/static.js.
const {AdminStatic}=require('./admin/static');const adminStatic=new AdminStatic({enabled:()=>admin.access.enabled});
const initial=()=>{let b={};const back=['R','N','B','Q','K','B','N','R'];for(let x=0;x<8;x++){b[x+',0']='b'+back[x];b[x+',1']='bP';b[x+',6']='wP';b[x+',7']='w'+back[x]}return b};
const key=(x,y)=>x+','+y, inside=(x,y)=>x>=0&&x<8&&y>=0&&y<8, color=p=>p?p[0]:'';
function fresh(){return{board:initial(),turn:'w',status:'BRANCAS JOGAM',game_over:false,promotion_pending:false,promotion_color:'w',promotion_cell:[-1,-1],last_from:[-1,-1],last_to:[-1,-1],captured_white:[],captured_black:[],move_count:0}}
function pseudo(g,x,y){const out=[],p=g.board[key(x,y)];if(!p)return out;const c=p[0],t=p[1],ray=(dx,dy)=>{let a=x+dx,b=y+dy;while(inside(a,b)){const q=g.board[key(a,b)];if(!q)out.push([a,b]);else{if(q[0]!=c)out.push([a,b]);break}a+=dx;b+=dy}};
if(t==='P'){const dy=c==='w'?-1:1,sy=c==='w'?6:1;if(inside(x,y+dy)&&!g.board[key(x,y+dy)]){out.push([x,y+dy]);if(y===sy&&!g.board[key(x,y+2*dy)])out.push([x,y+2*dy])}for(const dx of[-1,1]){const q=g.board[key(x+dx,y+dy)];if(q&&q[0]!==c)out.push([x+dx,y+dy])}}
else if(t==='N')for(const[d,e]of[[1,2],[2,1],[2,-1],[1,-2],[-1,-2],[-2,-1],[-2,1],[-1,2]]){const a=x+d,b=y+e,q=g.board[key(a,b)];if(inside(a,b)&&(!q||q[0]!==c))out.push([a,b])}
else if(t==='K'){for(let d=-1;d<=1;d++)for(let e=-1;e<=1;e++)if(d||e){const a=x+d,b=y+e,q=g.board[key(a,b)];if(inside(a,b)&&(!q||q[0]!==c))out.push([a,b])}}
else{let ds=[];if('RQ'.includes(t))ds.push([1,0],[-1,0],[0,1],[0,-1]);if('BQ'.includes(t))ds.push([1,1],[1,-1],[-1,1],[-1,-1]);for(const d of ds)ray(...d)}return out}
function attacked(g,x,y,by){for(const k in g.board){const [a,b]=k.split(',').map(Number),p=g.board[k];if(p[0]!==by)continue;if(p[1]==='P'){const dy=by==='w'?-1:1;if(b+dy===y&&Math.abs(a-x)===1)return true}else if(p[1]==='K'){if(Math.max(Math.abs(a-x),Math.abs(b-y))===1)return true}else if(pseudo(g,a,b).some(v=>v[0]===x&&v[1]===y))return true}return false}
function check(g,c){for(const k in g.board)if(g.board[k]===c+'K'){const[x,y]=k.split(',').map(Number);return attacked(g,x,y,c==='w'?'b':'w')}return true}
function legal(g,x,y){const p=g.board[key(x,y)];if(!p)return[];return pseudo(g,x,y).filter(([a,b])=>{const target=g.board[key(a,b)];if(target&&target[1]==='K')return false;delete g.board[key(x,y)];g.board[key(a,b)]=p;const ok=!check(g,p[0]);delete g.board[key(a,b)];g.board[key(x,y)]=p;if(target)g.board[key(a,b)]=target;return ok})}
function hasMove(g,c){for(const k in g.board){const[x,y]=k.split(',').map(Number);if(g.board[k][0]===c&&legal(g,x,y).length)return true}return false}
function update(g){const ck=check(g,g.turn),hm=hasMove(g,g.turn);if(!hm){g.game_over=true;g.status=ck?(g.turn==='b'?'XEQUE-MATE! BRANCAS VENCEM':'XEQUE-MATE! PRETAS VENCEM'):'EMPATE — AFOGAMENTO'}else g.status=ck?(g.turn==='b'?'XEQUE! PRETAS JOGAM':'XEQUE! BRANCAS JOGAM'):(g.turn==='b'?'PRETAS JOGAM':'BRANCAS JOGAM')}
function code(){let s;do{s='';for(let i=0;i<6;i++)s+=LETTERS[crypto.randomInt(LETTERS.length)]}while(rooms.has(s));return s}
function token(){return crypto.randomBytes(24).toString('hex')}
function send(ws,o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o))}
function state(r){const g=r.g;return{type:'state',revision:r.revision,board:Object.entries(g.board).map(([k,p])=>[...k.split(',').map(Number),p]),turn:g.turn,status:g.status,game_over:g.game_over,promotion_pending:g.promotion_pending,promotion_color:g.promotion_color,promotion_cell:g.promotion_cell,last_from:g.last_from,last_to:g.last_to,captured_white:g.captured_white,captured_black:g.captured_black,move_count:g.move_count,started:r.started,white_connected:!!r.w,black_connected:!!r.b,restart_votes:[...r.votes]}}
function broadcast(r){const s=state(r);send(r.w,s);send(r.b,s)}
function attach(ws,r,c){r[c]=ws;r.touched=Date.now();ws.room=r;ws.color=c;send(ws,{type:'welcome',room:r.code,color:c,token:r.tokens[c]});broadcast(r)}
function fail(ws,m){send(ws,{type:'error',message:m})}
// Tamanho máximo por mensagem: 8 KB em geral; só a foto de perfil (até 400 KB de imagem em base64)
// e o resumo da análise (lances de partidas longas) podem ser maiores. O tipo é conferido depois
// do JSON.parse (o Godot ordena as chaves, então "type" vem depois de "data"); acima de 600 KB o
// pacote é recusado antes de qualquer parse, e o limite de 20 mensagens/s vale antes do parse.
const MAX_PACKET=8192, MAX_BIG_PACKET=600*1024, BIG_TYPES={'acct_avatar_upload':MAX_BIG_PACKET,'analysis_record':64*1024};
function bigAllowed(m,len){const lim=m&&typeof m.type==='string'&&Object.prototype.hasOwnProperty.call(BIG_TYPES,m.type)?BIG_TYPES[m.type]:0;return len<=lim}
const server=http.createServer((req,res)=>{
  if(admin.owns(req))return void admin.handle(req,res);
  if(adminStatic.owns(req))return void adminStatic.handle(req,res);
  // Webhook do provedor de pagamento (V2). Corpo bruto é necessário para verificar a assinatura.
  if(req.method==='POST'&&(req.url==='/webhooks/payments'||String(req.url).startsWith('/webhooks/payments?'))){let raw='';req.on('data',d=>{raw+=d;if(raw.length>1e6)req.destroy()});req.on('end',async()=>{try{const r=await backend.payments.webhook(req,raw);res.writeHead(r.status,{'content-type':'text/plain'});res.end(r.body)}catch(e){console.error('webhook',e&&e.message);res.writeHead(500);res.end('error')}});return}
  res.writeHead(200,{'content-type':'text/plain'});res.end('FRAIHA multiplayer server\n')});
const wss=new WebSocketServer({server});
wss.on('connection',ws=>{ws.count=0;ws.rateAt=0;ws.on('message',raw=>{if(raw.length>MAX_BIG_PACKET)return ws.close(1009,'Packet too large');const sec=Math.floor(Date.now()/1000);if(ws.rateAt!==sec){ws.rateAt=sec;ws.count=0}if(++ws.count>20)return ws.close(1008,'Rate limit');let m;try{m=JSON.parse(raw)}catch{return raw.length>MAX_PACKET?ws.close(1009,'Packet too large'):undefined}if(raw.length>MAX_PACKET&&!bigAllowed(m,raw.length))return ws.close(1009,'Packet too large');if(m===null||typeof m!=='object'||Array.isArray(m)||typeof m.type!=='string')return fail(ws,'Mensagem inválida.');backend.presence.touch(ws);handle(ws,m)});ws.on('pong',()=>backend.presence.touch(ws));ws.on('close',()=>{backend.onClose(ws);const r=ws.room;if(r&&r[ws.color]===ws){r[ws.color]=null;r.votes.clear();r.touched=Date.now();broadcast(r)}})});
function handle(ws,m){const a=String(m.type||'');if(a==='ping')return send(ws,{type:'pong'});if(a.startsWith('acct_')||a.startsWith('ranked_')||a.startsWith('casual_')||a.startsWith('chat_')||a.startsWith('social_')||a.startsWith('dm_')||a.startsWith('invite_')||a.startsWith('analysis_')||a.startsWith('dev_')||a.startsWith('payment_')||a.startsWith('bot_')||a.startsWith('marcha_')||a.startsWith('party_')||a.startsWith('voice_')||a==='guest_auth')return void backend.handle(ws,m);if(!ws.room){if(a==='create'){if(rooms.size>=MAX_ROOMS)return fail(ws,'Servidor cheio. Tente novamente em alguns minutos.');const c=code(),r={code:c,g:fresh(),w:null,b:null,started:false,revision:0,votes:new Set(),touched:Date.now(),tokens:{w:token(),b:token()}};rooms.set(c,r);return attach(ws,r,'w')}if(a==='join'){const r=rooms.get(String(m.room||'').trim().toUpperCase());if(!r)return fail(ws,'Sala não encontrada ou expirada.');if(r.started)return fail(ws,'Esta sala já tem dois jogadores. Use Reconectar para voltar.');r.started=true;return attach(ws,r,'b')}if(a==='resume'){const r=rooms.get(String(m.room||''));if(!r)return fail(ws,'A sala expirou ou o servidor reiniciou.');const c=['w','b'].find(c=>r.tokens[c]===String(m.token||''));if(!c)return fail(ws,'Não foi possível recuperar esta sessão.');if(r[c])return fail(ws,'Esta sessão ainda está conectada em outra janela.');return attach(ws,r,c)}return fail(ws,'Crie ou entre em uma sala primeiro.')}
const r=ws.room,g=r.g,c=ws.color;if(a==='leave'||a==='resign'){if(r.started&&!g.game_over){g.game_over=true;g.status='DESISTÊNCIA — '+(c==='w'?'PRETAS VENCEM':'BRANCAS VENCEM');g.promotion_pending=false;r.revision++}if(a==='leave'){r[c]=null;ws.room=null}broadcast(r);return}
if(!r.started||!r.w||!r.b)return fail(ws,'Aguardando a conexão do outro jogador.');if(a==='restart'){r.votes.add(c);if(r.votes.size===2){r.g=fresh();r.votes.clear();r.revision++}broadcast(r);return}if(Number(m.revision)!==r.revision){fail(ws,'O tabuleiro foi atualizado. Tente a jogada novamente.');return broadcast(r)}if(g.game_over)return fail(ws,'Partida encerrada.');
if(a==='move'){if(g.promotion_pending||c!==g.turn)return fail(ws,'Aguarde seu turno.');const f=m.from,t=m.to;if(!Array.isArray(f)||!Array.isArray(t)||f.length!==2||t.length!==2)return fail(ws,'Jogada inválida.');const [x,y]=f.map(Number),[u,v]=t.map(Number),p=g.board[key(x,y)];if(!inside(x,y)||!inside(u,v)||!p||p[0]!==c||!legal(g,x,y).some(q=>q[0]===u&&q[1]===v))return fail(ws,'Movimento não permitido.');const victim=g.board[key(u,v)];if(victim)(victim[0]==='w'?g.captured_white:g.captured_black).push(victim);delete g.board[key(x,y)];g.board[key(u,v)]=p;g.last_from=[x,y];g.last_to=[u,v];g.move_count++;if(p[1]==='P'&&((p[0]==='w'&&v===0)||(p[0]==='b'&&v===7))){g.promotion_pending=true;g.promotion_cell=[u,v];g.promotion_color=p[0]}g.turn=g.turn==='w'?'b':'w';if(!g.promotion_pending)update(g)}
else if(a==='promote'){const k=String(m.kind||'');if(!g.promotion_pending||g.promotion_color!==c||!['Q','R','B','N'].includes(k))return fail(ws,'Promoção inválida.');g.board[key(...g.promotion_cell)]=c+k;g.promotion_pending=false;g.promotion_cell=[-1,-1];update(g)}else return fail(ws,'Ação desconhecida.');
r.votes.clear();r.revision++;r.touched=Date.now();broadcast(r)}
setInterval(()=>{for(const[c,r]of rooms)if(!r.w&&!r.b&&Date.now()-r.touched>TTL)rooms.delete(c)},20000);
server.listen(PORT,'0.0.0.0',()=>console.log('FRAIHA WebSocket server listening on '+PORT));
